language: php

php:
  - 7.1
  - 7.2

env:
  - CODECOV_TOKEN="751a65e7-7962-454d-9080-697e0d8e4954"

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - touch database/ticketbeast.sqlite
  - php artisan key:generate
  - php artisan migrate:install
  - php artisan migrate

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - node_modules
    - vendor
