language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - touch database/ticketbeast.sqlite
  - php artisan key:generate
  - php artisan migrate:install
  - php artisan migrate

script:
  - vendor/bin/phpunit

cache:
  directories:
    - node_modules
    - vendor
